### PR TITLE
Adding {:as :json-kebab-keys} for camel-snake-kebab response coercion

### PR DESCRIPTION
**Pull request by oliyh**
Hi,
I found the following very useful when preferring to deal with idiomatic map keys, I hope others will find it useful too.

### CODE REVIEW

**Comment by dakrone** [comment]
Hi @oliyh I'm not sure if this should be included in clj-http, since the body coercion is pluggable at runtime, I'm not sure whether this should be merged

**Comment by oliyh** [comment]
Completely up to you of course - for me, it's a great addition to promote idiomatic clojure code. Won't be offended if you decide to close this without merging :)

**Comment by dakrone** [comment]
Okay, thanks for being okay with it, how about this though, if you want to add an example of this to the `examples/` folder for how to extend the body coercion I think that would be **great**! Then it's still available for anyone to see

**Comment by oliyh** [comment]
Yes that makes perfect sense. I'll rework this PR and let you know when it's ready!

**Comment by oliyh** [comment]
Hi @dakrone I've updated the PR with an example as suggested, let me know what you think.

**Comment by dakrone** [comment]
Great, thanks @oliyh!

**Pull request merged**
