### PR TITLE
Support of output coercion of x-www-form-urlencoded content type

### PR DESCRIPTION
**Pull request by propan**
Would you mind adding this feature?

### CODE REVIEW

**Comment by dakrone** [comment]
Hi @propan, thanks for the pull request!

It looks like this is missing adding the `ring-codec` dependency in project.clj. Would you be able to add that to the project and make it optional the same way that cheshire and transit-clj are? (where we check and only enable it if it's available)

**Comment by propan** [comment]
@dakrone, sure. I'll update the pull request.

**Comment by propan** [comment]
@dakrone, please have a look at the updated PR. I hope I didn't miss anything.

**Comment by dakrone** [comment]
Thanks for the updates, merged!

**Pull request merged**
