### PR TITLE
Run all tests with TravisCI

### PR DESCRIPTION
**Pull request by rymndhng**
To answer: Why not run the integration tests in TravisCI?

### CODE REVIEW

**Comment by rymndhng** [comment]
Looks like there's a few issues in the tests:

1. SSL Keystore tests fail
2. Unable to run ipv6 tests because of TravisCI build container environment

**Comment by dakrone** [comment]
Unfortunately I've never been able to get the integration tests to pass in Travis, I think they do some sandboxing that won't let everything work the way we expect.

**Comment by rymndhng** [comment]
I noticed the IPV6 tests probably won’t work based on their documentation. I could try setting up circleci as an alternative they support ipv6 for local testing according to their documentation.

I haven’t been able to get the conn_mgr tests working locally though, is there some additional setup steps I need to do?

**Comment by dakrone** [comment]
> I haven’t been able to get the conn_mgr tests working locally though, is there some additional setup steps I need to do?

On the 3.x branch? What failures are you getting?

**Comment by rymndhng** [comment]
I see these errors:

```
lein test :only clj-http.test.conn-mgr-test/ssl-client-cert-get

FAIL in (ssl-client-cert-get) (conn_mgr_test.clj:120)
expected: (= 200 (:status resp))
  actual: (not (= 200 403))

lein test :only clj-http.test.conn-mgr-test/ssl-client-cert-get-async

FAIL in (ssl-client-cert-get-async) (conn_mgr_test.clj:143)
expected: (= 200 (:status (deref resp 1000 {:status :timeout})))
  actual: (not (= 200 :timeout))
```

I also noticed they're only present in the openjdk11 travis build [link](https://travis-ci.org/dakrone/clj-http/jobs/568681785#L675-L693). I also happen to be running openjdk11 locally.

**Comment by SuperStevenZ** [comment]
I'm also seeing the same error message that @rymndhng mentioned above at `[clj-http "3.9.0"]` which results in `:ssl-client-cert` always is `nil` in the requests from `Jetty`'s perspective.

**Comment by rymndhng** [comment]
Closed in favor of #550

**Pull request closed without merging**
