### PR TITLE
Populate the :trace-redirects response field

### PR DESCRIPTION
**Pull request by Abhiroop**
Fix for issue [#326](https://github.com/dakrone/clj-http/issues/326)

### CODE REVIEW

**Comment by dakrone** [comment]
Thanks! I'm traveling right now but I will review this as soon as I get back

**Comment by dakrone** [comment]
@Abhiroop thanks for submitting this!

Unfortunately, this causes a lot of test failures when running `lein test :all` (the integration tests) due to a NullPointerException if there are no attributes. Can you fix that so it correctly handles the null case?

**Comment by devth** [comment]
Just ran into this. @Abhiroop, are you able to fixup the NPE? Thanks!

**Comment by Abhiroop** [comment]
@devth I am planning to check it this weekend.

**Comment by andrew-potgieter** [comment]
@Abhiroop Have you had any luck with this?

**Comment by dakrone** [comment]
I believe this is closed by #341

**Pull request closed without merging**
