### PR TITLE
Add ring like async HTTP request support

### PR DESCRIPTION
**Pull request by bobotu**
I added a ring like CPS async HTTP client support. The request can simply like

`(client/get "https://www.google.com" {:async? true} respond raise)`

`respond` can simply be a promise or more complex function, `raise` is the same.
The exception which throw by `wrap-exceptions` now  is passed to `raise` handler.

There is also a `with-async-connection-pool` macro, which can make all async request in this context using one `PoolingNHttpClientConnectionManager` and shutdown the conn-mgr when all request is finished.

Also provide a helper function `reuse-pool` which used in `respond` callback, it take a new request options map and a response then return a new options map that can let the client reuse the connection pool. The usage of connection pool can see `t-with-async-pool` and `t-reuse-async-pool` in `client-test`.

I think async HTTP request is important in the future and ring also added async support, I tried to add a ring like async request support.

### CODE REVIEW

**Comment by dakrone** [comment]
@bobotu this is awesome, I don't want you to think I haven't seen this, it will just take me quite a while to review it! (other people reviewing would be appreciated also!)

**Comment by ddillinger** [comment]
I've been looking at it too. It's neat! I do have one question:

Is there any (degenerate) case in `with-async-connection-pool` where `.shutdown` won't be called? Specifically I am thinking of edge cases where `:release` wouldn't have fired, or fired twice and now `count` is _less than_ 0, defensive things like that.

**Comment by bobotu** [comment]
@ddillinger I considered some cases again. And here is what I have considered:

In the respond of a request:
* If there is any exception thrown by the `wrap-request-timing` or user's middleware, this exception will caught by the `try...catch` in the `completed` callback of client or passed to the raise handler, in any case the `:release` will be invoked once.If user's middleware use the `raise` handler, the respond given by `warp-async-pooling` won't be invoked and `:release` will invoke once in `raise`.

* If there is any exception thrown between the `wrap-async-pooling` and `wrap-exceptions`, because the middleware in this area will simply thrown the exception, this exception will also caught by  `completed` callback, in this case `:release` will be invoked once.

* If If there is any exception thrown in `wrap-exceptions` and middleware after it, unfortunately, `:release` will be invoked twice in the first commit. Because in the first commit I implement the `wrap-exceptions` in an incorrect way, `try...catch` the whole call of `respond`, any exception thrown after this middleware will be caught by it, then this middleware will invoke `raise` handler for the first time. After `raise` return the `:release` after `respond` in the `wrap-async-pooling` will be invoked for the second time. This question is easy to fix, because the `completed` callback `try...catch` the whole `respond`, `wrap-exceptions` can simply thrown the exception like other middleware the `try...catch` in `completed` will invoke `raise` and `:release` in `wrap-async-pooling` will never be invoked.

* If there is no exception in the respond call stack, the `:allocate` will be invoked once when this middleware be invoked, and `:release` will also be invoked once when finished the whole respond. The `all-requested#` atom also insure connection manager wouldn't be closed before all no nested async request start.

* If there are some nested request, I provide a `reuse-poll` helper function to build correct request. Because the request is start in the`respond` of parent request, the nested request will block the parent `respond` until nested request start. After that nested request's `:allocate` will be invoked first and then parent request's `:release` be invoked. Because the nested request have it's own call stack and exception handler in other thread, the condition of nested request is same as above.

In the start of a request:
* If there is exception thrown in the middleware before `wrap-async-pooling` wouldn't invoke the `:allocate` and `:release` will never be invoked. This condition in nested request is quite interesting, if user doesn't wrap the nested request using `try...catch` the exception will caught by parent request's `try...catch` and parent request's `raise` will be invoked, user will know there is exception and `:release` also be invoked correctly, if user `try...catch` the nested request, the parent request's `respond` will invoke `:release` correctly.

* If there is exception thrown after `wrap-async-pooling`, unfortunately, there is also some question in the init commit. Because `:allocate` have invoked, but the `:release` won't be invoke if user's middleware doesn't call `raise` in this case. Maybe wrap the invoke of `client` in `wrap-async-pooling` using `try...catch` will solve this problem, because the start of a request in one thread and respond in another, this wrap wouldn't invoke the `:release` in `respond`.

So I found two edge case, I will modify the code and add some tests to test these case tomorrow. If there is any other problem please tell me and I will try to fix them.

**Comment by ddillinger** [comment]
This looks good to me, there are just a couple of things:

* there's a conflict with https://github.com/dakrone/clj-http/commit/cddeb3e5d6d27dab3dd170c7c10b30af4fe12389 that needs resolution
* The new public API pieces, e.g. `wrap-async-pooling, `with-async-connection-pool`, `http-async-client` etc., should have a little documentation so people know these cool new things exist and how to get started using them

**Comment by dakrone** [comment]
Merged this, thanks very much @bobotu for the code and @ddillinger for the review!

**Comment by ponimas** [comment]
is there any release plan?
really miss async requests

**Comment by dakrone** [comment]
@ponimas this is already in the 3.3.0 release, which was released a while ago. You should be able to use it!

**Comment by ponimas** [comment]
@dakrone probably, i'm doing something wrong... 
```
✗ lein try clj-http "3.3.0"
nREPL server started on port 64398 on host 127.0.0.1 - nrepl://127.0.0.1:64398
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.8.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_92-b14
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (require '[clj-http.client :as http])
nil
user=> (def z (http/get "http://ya.ruf" {:async? true} (fn [x] (println "hey") (fn [x] (println "boo")))))

CompilerException java.net.UnknownHostException: ya.ruf: unknown error, compiling:(form-init8349940740742707089.clj:1:8)
user=> (def z (http/get "http://ya.ru" {:async? true} (fn [x] (println "hey") (fn [x] (println "boo")))))
#'user/z
user=> (keys z)
(:request-time :repeatable? :protocol-version :streaming? :chunked? :cookies :reason-phrase :headers :orig-content-encoding :status :length :body :trace-redirects)
```

**Comment by dakrone** [comment]
@ponimas nope, it's not you, I just fail at reading git logs :(

I'll do a new release with this now!

**Comment by dakrone** [comment]
@ponimas I have released 3.4.0 with this PR included, thanks for reminding me!

**Pull request merged**
