### PR TITLE
Prepare 3.10.2 release notes

### PR DESCRIPTION
**Pull request by rymndhng**
We've had some really good contributions in the last little while. I think it is a good time to release a patch new version of `clj-http`.

### CODE REVIEW

**Comment by rymndhng** [comment]
@dakrone I believe this is something that requires you to perform. 

However, if you are looking to spread the maintainer work, I'd be happy to help publish the next version (if you are able to grant me access to the clojars group 😁)

**Comment by dakrone** [comment]
@rymndhng it would be good to have more than just me that could publish it, what is your clojars username?

**Comment by rymndhng** [comment]
> It would be good to have more than just me that could publish it, what is your clojars username?

Cool, glad you're onboard with it 😁. My clojars username is `rymndhng`.

**Comment by dakrone** [comment]
Okay, you should be added, lemme know if it works for you! (sorry for the delay, was away for a family emergency)

**Comment by rymndhng** [comment]
> Okay, you should be added, lemme know if it works for you! (sorry for the delay, was away for a family emergency)

No problem at all! 🤗

**Comment by rymndhng** [comment]
Credentials worked! 3.10.2 is out 🎉

Link: https://clojars.org/clj-http/versions/3.10.2

**Pull request merged**
