### PR TITLE
Copy dynamic variables to async callbacks

### PR DESCRIPTION
**Pull request by tanzoniteblack**
Solves https://github.com/dakrone/clj-http/issues/465

### CODE REVIEW

**Comment by dakrone** [comment]
@tanzoniteblack thanks! would you also be willing to add a unit or integration test for this so we can make sure it doesn't break again in the future?

**Comment by tanzoniteblack** [comment]
@dakrone Happy to add a unit test for this, but could you point me to an existing unit test that would be a good model for creating a new test for this? (the unit tests in this project aren't immediately clear to me)

**Comment by tanzoniteblack** [comment]
@dakrone poking you again about advice on how to write a unit test for this? I suppose the test should be actually making a call with a dynamic variable (something akin to what I put in the related issue https://github.com/dakrone/clj-http/issues/465), but I'm not sure how to start an http server to talk to?

**Comment by dakrone** [comment]
@tanzoniteblack would it be possible to have an async callback in a test that checked the value of a dynamic variable? You gave an example in #465 of a var, instead of printing it, it can be a check that the variable is not `nil` (meaning it's be propagated correctly)

**Comment by tanzoniteblack** [comment]
@dakrone added a test that verified that the dynamic variables are being propagated with these changes. Made sure to run the tests before & after applying my changes to verify they failed beforehand and succeeded afterwards.

**Comment by tanzoniteblack** [comment]
The tests are passing on all jdk's except for 11...which is failing on installing jdk11, before any of our code gets executed: https://travis-ci.org/dakrone/clj-http/jobs/521803349#L421 . Not sure what I can do about that.

**Comment by dakrone** [comment]
Merged this, thanks for iterating on it @tanzoniteblack, I'll be cutting a new release soon with this change.

**Pull request merged**
