### PR TITLE
Remove all reflection

### PR DESCRIPTION
**Pull request by jeaye**
All tests pass locally. I would also highly recommend setting `*warn-on-reflection*` to `true`, to prevent these from showing up in the future.

Thanks!

### CODE REVIEW

**Comment by jeaye** [comment]
Any interest in this?

**Comment by dakrone** [comment]
@jeaye yes, I have just been swamped with work lately, I will get to it eventually if one of the other committers doesn't beat me to it.

**Comment by jeaye** [comment]
I appreciate the update! Cheers.

**Comment by dakrone** [comment]
This has been merged now, thanks!

**Comment by jeaye** [comment]
Thank you!

**Pull request merged**
