### PR TITLE
Allow arrays as nested values

### PR DESCRIPTION
**Pull request by clyfe**

### CODE REVIEW

**Comment by escherize** [comment]
I actually need this as well.

**Comment by clyfe** [comment]
@escherize https://gist.github.com/clyfe/b0d1ebfd99304f6e2a9c

**Comment by escherize** [comment]
That's a god approach. I don't see how I can add that code into a library that calls into clj-http, though.

**Comment by dakrone** [comment]
Sorry this too so long, merged into master and 2.x, do you need a release with this?

**Comment by clyfe** [comment]
@dakrone thanks! I don't need a release right away since I'm currently the middleware in the gist above, so release at your leisure!

**Pull request merged**
