### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by ghaskins**
Signed-off-by: Greg Haskins <greg@manetu.com>

### CODE REVIEW

**Comment by dakrone** [comment]
@ghaskins this appears to break the tests, can you take a look? It appears to be related to the `ring.util.codec` namespace.

**Comment by ghaskins** [comment]
@dakrone looking

**Comment by ghaskins** [comment]
Sorry I had missed the note on how to run 'lein all test' and only checked 'lein test'.  The problem seems to be isolated to the :1.6 profile.  Investigating now.

**Comment by ghaskins** [comment]
It seems that the simplest solution is to simply drop the 1.6 profile, as ring-codec only profiles as far back as 1.8.  Of course, I don't know what your users require, so this may not be a practical suggestion.  

According to https://en.wikipedia.org/wiki/Clojure#Language_overview

1.6 came out 3/2014 and 1.7 6/2015, so setting the floor at 1.7 is probably not terrible.  What do you think @dakrone ?

**Comment by ghaskins** [comment]
I added dropping 1.6 to the proposal.  Let me know if you want to take a different route and happy to oblige.

**Pull request closed without merging**
